## 我对这次的BP算法产生了非常大的疑问，虽然整体上和上次的代码一样，但是其中我改动了梯度更新的函数，因为根据西瓜书的算法来看的话，第48行代码应该有一个(1-L1)，但是改动了之后的算法准确率反而不如原来的BP算法，一时间竟然不知道谁对，看了很久..很久，推导的算法应该没有问题，但是就是不高...........

In [31]:
# 库函数的调用
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
import numpy as np


# 数据导入
digits = load_digits()
X = digits.data
Y = digits.target
## 数据归一化处理
X -= X.min()
X /= X.max()
## 拆分测试集和训练集
X_train,X_test,y_train,y_test = train_test_split(X,Y)  #默认3:1划分
## 标签二值化 --独热编码
labels_train = LabelBinarizer().fit_transform(y_train)  #标签二值化
labels_test = LabelBinarizer().fit_transform(y_test)  #标签二值化


# 函数的设置 --sigmoid函数 和 dsigmoid函数
def sigmoid(x):
    return 1/(1+np.exp(-x))
def dsigmoid(x):
    return x*(1-x)

# 神经网络的设置
class NeuralNetwork:
    def __init__(self, layers):
        self.V = np.random.random((layers[0]+1, layers[1]+1))*2-1
        self.W = np.random.random((layers[1]+1, layers[2]))*2-1

    def train(self, X, y, lr = 0.11, epochs = 10000):
        tran = np.ones([X.shape[0], X.shape[1]+1])
        tran[:,0:-1] = X
        X = tran

        for n in range(epochs+1):
            i = np.random.randint((X.shape[0]))
            x = [X[i]]
            x = np.atleast_2d(x)

            L1 = sigmoid(np.dot(x, self.V))
            L2 = sigmoid(np.dot(L1, self.W))

            L2_delta = (y[i]-L2)*dsigmoid(L2)
            L1_delta = (1-L1)*L2_delta.dot(self.W.T)

            self.W += lr * L1.T.dot(L2_delta)
            self.V += lr * x.T.dot(L1_delta)

            if n % 1000 == 0:
                predictions = []
                for j in range(X_test.shape[0]):
                    o = self.predict(X_test[j])
                    predictions.append(np.argmax(o))
                accuracy = np.mean(np.equal(predictions, y_test))
                print('epoch:', n, 'accuracy:', accuracy)

    def predict(self, x):
        #添加偏置
        temp = np.ones(x.shape[0] + 1)
        temp[0:-1] = x
        x = temp
        x = np.atleast_2d(x)  #转为二维数据

        L1 = sigmoid(np.dot(x, self.V))  #隐藏层输出
        L2 = sigmoid(np.dot(L1, self.W))  #输出层输出
        return L2

nm = NeuralNetwork([64,100,10])  #创建网络
print('start')
nm.train(X_train,labels_train,epochs=50000)
print('end')

epoch: 11000 accuracy: 0.8866666666666667
epoch: 12000 accuracy: 0.86
epoch: 13000 accuracy: 0.8755555555555555
epoch: 14000 accuracy: 0.8866666666666667
epoch: 15000 accuracy: 0.8888888888888888
epoch: 16000 accuracy: 0.8888888888888888
epoch: 17000 accuracy: 0.8977777777777778
epoch: 18000 accuracy: 0.8777777777777778
epoch: 19000 accuracy: 0.8888888888888888
epoch: 20000 accuracy: 0.8888888888888888
epoch: 21000 accuracy: 0.8666666666666667
epoch: 22000 accuracy: 0.8644444444444445
epoch: 23000 accuracy: 0.8622222222222222
epoch: 24000 accuracy: 0.8444444444444444
epoch: 25000 accuracy: 0.8444444444444444
epoch: 26000 accuracy: 0.8511111111111112
epoch: 27000 accuracy: 0.8377777777777777
epoch: 28000 accuracy: 0.86
epoch: 29000 accuracy: 0.8577777777777778
epoch: 30000 accuracy: 0.8822222222222222
epoch: 31000 accuracy: 0.8644444444444445
epoch: 32000 accuracy: 0.8533333333333334
epoch: 33000 accuracy: 0.8844444444444445
epoch: 34000 accuracy: 0.8644444444444445
epoch: 35000 accurac

# CNN算法


In [34]:
import torchvision
from torch import nn
from torch.nn import Sequential, Conv2d, MaxPool2d, Flatten,Linear


## 导入数据
train_data = torchvision.datasets.CIFAR10(root='./dataset' ,train = True, transform=torchvision.transforms.ToTensor(), download=True)
test_data = torchvision.datasets.CIFAR10(root='./dataset', train = False, transform=torchvision.transforms.ToTensor(), download=True)


Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified


In [36]:
## 训练模型
class Tudui(nn.Module):
    def __init__(self):
        super(Tudui,self).__init__()
        self.model1 = Sequential(
            Conv2d(3, 32, 5, 1, padding=2),
            MaxPool2d(2),
            Conv2d(32, 32, 5, 1, padding=2),
            MaxPool2d(2),
            Conv2d(32, 64, 5, 1, padding=2),
            MaxPool2d(2),
            Flatten(),
            Linear(1024, 64),
            Linear(64, 10))
    def forward(self, x):
        x = self.model1(x)
        return x

### 自研卷积网络


In [68]:
## 自研卷积层
input1 = np.random.randint(1, 100, (5, 5))
Kerual = np.random.randint(0, 3, (3, 3))
print(input, "\n\n", Kerual)

[[11 88 38 76 35]
 [ 6 73 12 97 79]
 [70 78  4 85 55]
 [37 73  9 12  2]
 [78 63 91 94 53]] 

 [[2 0 1]
 [2 0 2]
 [1 1 0]]


In [113]:
### 卷积层操作
step_lie = input1.shape[1] - Kerual.shape[1]
step_han = input1.shape[0] - Kerual.shape[0]

output_1 = np.ones((step_han+1,step_lie+1))

for i in range(step_han+1):
    for j in range(step_lie+1):
        output_1[i, j] = np.dot(input1[i:i+3, j:j+3],Kerual).sum()
output_1

array([[1325., 1449., 1532.],
       [1285., 1160., 1123.],
       [1619., 1440., 1296.]])